name: env
description: A repository that manages enviromental variables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  envied: ^1.0.0
  envied_generator: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
